set_property IOSTANDARD LVCMOS33 [get_ports A]
set_property IOSTANDARD LVCMOS33 [get_ports Y1]
set_property IOSTANDARD LVCMOS33 [get_ports Sel]
set_property IOSTANDARD LVCMOS33 [get_ports Y0]
set_property PACKAGE_PIN V17 [get_ports A]
set_property PACKAGE_PIN V16 [get_ports Sel]
set_property PACKAGE_PIN U16 [get_ports Y0]
set_property PACKAGE_PIN E19 [get_ports Y1]
